/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecentStudentConductRouteImport } from './routes/recentStudentConduct'
import { Route as RecentLessonsRouteImport } from './routes/recentLessons'
import { Route as RecentAssessmentRouteImport } from './routes/recentAssessment'
import { Route as MyFilesRouteImport } from './routes/myFiles'
import { Route as HelpFaqsRouteImport } from './routes/help-faqs'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentStudentConductRoute = RecentStudentConductRouteImport.update({
  id: '/recentStudentConduct',
  path: '/recentStudentConduct',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentLessonsRoute = RecentLessonsRouteImport.update({
  id: '/recentLessons',
  path: '/recentLessons',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentAssessmentRoute = RecentAssessmentRouteImport.update({
  id: '/recentAssessment',
  path: '/recentAssessment',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFilesRoute = MyFilesRouteImport.update({
  id: '/myFiles',
  path: '/myFiles',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqsRoute = HelpFaqsRouteImport.update({
  id: '/help-faqs',
  path: '/help-faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help-faqs': typeof HelpFaqsRoute
  '/myFiles': typeof MyFilesRoute
  '/recentAssessment': typeof RecentAssessmentRoute
  '/recentLessons': typeof RecentLessonsRoute
  '/recentStudentConduct': typeof RecentStudentConductRoute
  '/settings': typeof SettingsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help-faqs': typeof HelpFaqsRoute
  '/myFiles': typeof MyFilesRoute
  '/recentAssessment': typeof RecentAssessmentRoute
  '/recentLessons': typeof RecentLessonsRoute
  '/recentStudentConduct': typeof RecentStudentConductRoute
  '/settings': typeof SettingsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help-faqs': typeof HelpFaqsRoute
  '/myFiles': typeof MyFilesRoute
  '/recentAssessment': typeof RecentAssessmentRoute
  '/recentLessons': typeof RecentLessonsRoute
  '/recentStudentConduct': typeof RecentStudentConductRoute
  '/settings': typeof SettingsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/dashboard'
    | '/feedback'
    | '/help-faqs'
    | '/myFiles'
    | '/recentAssessment'
    | '/recentLessons'
    | '/recentStudentConduct'
    | '/settings'
    | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/dashboard'
    | '/feedback'
    | '/help-faqs'
    | '/myFiles'
    | '/recentAssessment'
    | '/recentLessons'
    | '/recentStudentConduct'
    | '/settings'
    | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/dashboard'
    | '/feedback'
    | '/help-faqs'
    | '/myFiles'
    | '/recentAssessment'
    | '/recentLessons'
    | '/recentStudentConduct'
    | '/settings'
    | '/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpFaqsRoute: typeof HelpFaqsRoute
  MyFilesRoute: typeof MyFilesRoute
  RecentAssessmentRoute: typeof RecentAssessmentRoute
  RecentLessonsRoute: typeof RecentLessonsRoute
  RecentStudentConductRoute: typeof RecentStudentConductRoute
  SettingsRoute: typeof SettingsRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recentStudentConduct': {
      id: '/recentStudentConduct'
      path: '/recentStudentConduct'
      fullPath: '/recentStudentConduct'
      preLoaderRoute: typeof RecentStudentConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recentLessons': {
      id: '/recentLessons'
      path: '/recentLessons'
      fullPath: '/recentLessons'
      preLoaderRoute: typeof RecentLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recentAssessment': {
      id: '/recentAssessment'
      path: '/recentAssessment'
      fullPath: '/recentAssessment'
      preLoaderRoute: typeof RecentAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myFiles': {
      id: '/myFiles'
      path: '/myFiles'
      fullPath: '/myFiles'
      preLoaderRoute: typeof MyFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-faqs': {
      id: '/help-faqs'
      path: '/help-faqs'
      fullPath: '/help-faqs'
      preLoaderRoute: typeof HelpFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  HelpFaqsRoute: HelpFaqsRoute,
  MyFilesRoute: MyFilesRoute,
  RecentAssessmentRoute: RecentAssessmentRoute,
  RecentLessonsRoute: RecentLessonsRoute,
  RecentStudentConductRoute: RecentStudentConductRoute,
  SettingsRoute: SettingsRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
