
export const KPIList = [
  "Image, Neatness, and Orderliness ",
  "GROWTH MIND-SET, OPEN-MINDEDNESS, AND CONTINUOUS LEARNING",
  "RESPECT, HONESTY, AND RULE-ABIDING",
  "STOICISM, EMOTIONAL CONTROL, AND SELF-DISCIPLINE",
  "PATIENCE, FLEXIBILITY, AND ADAPTABILITY",
  "PASSION, DRIVE, AND SELF-MOTIVATION",
  "PASSION, DRIVE, AND SELF-MOTIVATION",
  "OPTIMISM, SELF-CONFIDENCE, AND POSITIVE-MINDEDNESS",
  "HARD-WORK, RESILIENCE, AND PERSISTENCE",
  "PUNCTUALITY, TIMELINESS, AND TIME-MANAGEMENT",
]